datasource:
  url: root:root@tcp(10.8.4.190:3306)/master?charset=utf8&parseTime=True&loc=Asia%2fShanghai
  idleCon: 10
  openCon: 200
  showSQL: true
  showExecTime: true

rocketmq:
  nameSrv: 10.8.4.190:9876
  broker: 10.8.4.190:10909
  topic: go-web
  producer: producer
  consumer: consumer
redis:
  url: 10.8.4.190:6379